blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.inicio,name='inicio'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contacto/$', views.contacto, name='contacto'),
    url(r'^publicaciones/', include('publicaciones.urls')),
]

blog/publicaciones/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'publicaciones'
urlpatterns = [
    url(r'^c-p$', views.crearPublicacion, name='crearPublicacion'),
    url(r'^m-p/(?P<titulo_formateado>[a-zA-Z0-9-]+)', views.modificarPublicacion, name='modificarPublicacion'),
    url(r'^(?P<titulo_formateado>[a-zA-Z0-9-]+)', views.detalle, name='detalle'),
]

blog/publicaciones/models.py
from django.db import models

# Create your models here.

class Publicacion(models.Model):
    titulo = models.CharField(max_length=450)
    contenido = models.TextField()
    fecha = models.DateField(auto_now=False,auto_now_add=True)
    titulo_formato = models.CharField(max_length=80,null=True)

    def __str__(self):
        return self.titulo

    def crear_titulo_formateado(self):
        self.save()
        titulo = self.titulo
        titulo = titulo.split()
        titulo_formateado = str(self.pk) +'-' + '-'.join(titulo)

        self.titulo_formato = titulo_formateado

        self.save()

    class Admin:
        list_display = ('titulo', 'fecha' , 'titulo_formato')
        list_filter = ('titulo', 'fecha')
        ordering = ('-fecha')
        search_fields = ('titulo')


class Comentario(models.Model):
    contenido = models.TextField()
    fecha = models.DateField(auto_now=False,auto_now_add=True)
    publicacion = models.ForeignKey(Publicacion,on_delete=models.CASCADE)


    def __str__(self):
        return str(self.fecha) + ' Comentario hecho a la publicacion:  ' +str(self.publicacion)


    class Admin:
        ordering = ('-fecha')
        search_fields = ('contenido')

blog/blog/forms.py
from django import forms

#Formulario de contacto
class ContactoForm(forms.Form):

    asunto = forms.CharField()
    nombre = forms.CharField(required=True)
    email = forms.EmailField()
    #Por parámetro le estamos especificando a forms.CharField que la casilla que se presentará será mas grande
    mensaje = forms.CharField(widget=forms.Textarea)


    #Dato que necesitamos enviar un email con estos datos debemos de separar las cadenas de los campos email
    def formato_email(self):
        try:
            #Me devuelve el campo email
            email = self.cleaned_data.get('email')
            #Separamos las partes del email
            email_base, proveedor = email.split('@')
            #Separamos el dominio del email de la extensión de este
            dominio, extension = proveedor.split('.')

        except ValueError:
            print('Hubo un error en el email')

        return email

blog/publicaciones/forms.py
from django import forms
from .models import Comentario, Publicacion


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido','publicacion']


class PublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicacion
        fields = ['titulo','contenido']

blog/blog/views.py
from django.shortcuts import render
from publicaciones.models import Publicacion
from .forms import ContactoForm
from django.core.mail import send_mail

# Create your views here.
def inicio(request):

    lista_publicaciones = Publicacion.objects.all().order_by('fecha')

    contexto = {
        'lista_publicaciones': lista_publicaciones
    }

    return render(request,'inicio.html',contexto)


def about(request):

    contexto = {}

    return render(request, 'about.html', contexto)




def contacto(request):

    form = ContactoForm(request.POST or None)



    if form.is_valid():

        form_asunto = form.cleaned_data.get('asunto')
        form_email = form.cleaned_data.get('email')
        form_mensaje = form.cleaned_data.get('mensaje')
        form_nombre = form.cleaned_data.get('nombre')


        email_asunto = 'Form de contacto'
        email_from = form_email
        email_to = ['pedroesparzaaa@gmail.com']
        email_mensaje = '%s: %s enviado por %s' %(form_nombre, form_mensaje, form_email)

        send_mail(
            email_asunto,
            email_mensaje,
            email_from,
            email_to,
            fail_silently=False,
        )


    contexto = {
            'form' : form
    }

    return render(request, 'contacto.html', contexto)

blog/publicaciones/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Publicacion
from .forms import ComentarioForm, PublicacionForm


def detalle(request, titulo_formateado):
    publicacion = get_object_or_404(Publicacion, titulo_formato=titulo_formateado)
    form = ComentarioForm(request.POST or None)
    form.publicacion = publicacion
    if form.is_valid():

        form.save()
        form = ComentarioForm()

    context = { 'publicacion':publicacion,
                'form':form }
    return render(request,'publicaciones/detalle_publicacion.html', context)


def crearPublicacion(request):

    form = PublicacionForm(request.POST or None)
    flag = 'nuevo'

    if form.is_valid():
        publicacion = form.save()
        publicacion.crear_titulo_formateado()
        form = PublicacionForm()

    context = {'form': form,
                'flag': flag}

    return render(request,'publicaciones/form_publicacion.html',context)


def modificarPublicacion(request, titulo_formateado):

    publicacion = get_object_or_404(Publicacion, titulo_formato=titulo_formateado)
    form = PublicacionForm(request.POST or None, instance=publicacion)
    flag = 'modificar'

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('publicaciones:detalle',publicacion.titulo_formato)

    context = {'form': form,
                'flag': flag}

    return render(request,'publicaciones/form_publicacion.html',context)

blog/templates/about.html
{% extends 'base.html' %}
{% block title%} Acerca de{% endblock %}

{% block template_conf_content %}
    
{%endblock%}
{% block active_about %}active{% endblock %}
{% block body%}
        <div class="jumbotron">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        <h2>Blog.com <small>El mejor blog del mundo</small></h2>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi quisquam repudiandae sed, ratione eveniet natus beatae, ipsam. Quo, tempora, libero.
                        </p>
                    </div>
                    <div class="col-xs-12 col-sm-3 col-sm-offset-3">
                        <div class="thumbnail">
                            <img src="https://www.webnode.com/blog/wp-content/uploads/2016/10/Blog-intro.jpg" class="img-responsive" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3 bg-primary">
                <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi sed nobis suscipit, dolore debitis dolores corrupti possimus temporibus officia, nesciunt tempore magni deleniti natus maiores voluptatibus ex recusandae ipsum, minus.</div>
                <div>Obcaecati atque quam quos consectetur perferendis ad, dolore eos fuga necessitatibus facilis, amet. Error quas, ipsum, at temporibus harum commodi iusto rem facere neque animi sit amet illo consequuntur aliquid?</div>
                <div>Maxime numquam, minus ducimus quod, molestiae repellat cum dolor veritatis laudantium debitis magnam officiis asperiores, laborum corporis. Atque, placeat, quas hic pariatur nesciunt necessitatibus incidunt a ab eum enim. Perferendis.</div>
                
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 bg-info">
                <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum magni eum, earum fuga, odit, minus nostrum iste illo totam delectus, similique! Quis perferendis numquam eos obcaecati consequuntur, repellendus similique quas?</div>
                <div>Quia eius sunt consectetur doloribus, perspiciatis laborum veritatis omnis fugiat quos. Odio porro amet, sunt ea, dolor voluptatibus ut illum cumque, distinctio mollitia veritatis at. Sequi labore et esse, tenetur!</div>
                <div>Dolores dolorem veniam officia, sunt. Voluptatum aut autem quo laborum eum eaque alias maiores distinctio molestias, nesciunt. Illo commodi sequi in fugiat ducimus, inventore sint eligendi aliquam. Quo, magni beatae!</div>
                <div>In quaerat, ipsa? Quae excepturi odit praesentium magni est ea. Omnis saepe, vel reprehenderit? Placeat ad deleniti unde, dolor vero alias? Delectus minima laudantium vel, sit saepe, voluptatem cupiditate dolore.</div>
                
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-xs-12 col-sm-6 col-md-3 bg-success">
                <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi sed nobis suscipit, dolore debitis dolores corrupti possimus temporibus officia, nesciunt tempore magni deleniti natus maiores voluptatibus ex recusandae ipsum, minus.</div>
                <div>Obcaecati atque quam quos consectetur perferendis ad, dolore eos fuga necessitatibus facilis, amet. Error quas, ipsum, at temporibus harum commodi iusto rem facere neque animi sit amet illo consequuntur aliquid?</div>
                <div>Maxime numquam, minus ducimus quod, molestiae repellat cum dolor veritatis laudantium debitis magnam officiis asperiores, laborum corporis. Atque, placeat, quas hic pariatur nesciunt necessitatibus incidunt a ab eum enim. Perferendis.</div>
                
            </div>
            
            <div class="col-xs-12 col-sm-6 col-md-3 bg-warning">
                <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi sed nobis suscipit, dolore debitis dolores corrupti possimus temporibus officia, nesciunt tempore magni deleniti natus maiores voluptatibus ex recusandae ipsum, minus.</div>
                <div>Obcaecati atque quam quos consectetur perferendis ad, dolore eos fuga necessitatibus facilis, amet. Error quas, ipsum, at temporibus harum commodi iusto rem facere neque animi sit amet illo consequuntur aliquid?</div>
                <div>Maxime numquam, minus ducimus quod, molestiae repellat cum dolor veritatis laudantium debitis magnam officiis asperiores, laborum corporis. Atque, placeat, quas hic pariatur nesciunt necessitatibus incidunt a ab eum enim. Perferendis.</div>
                
            </div>
        </div>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
     <link rel="stylesheet" href="../static/css/bootstrap.min.css">

    <link rel="stylesheet" href="../static/css/estilos.css">


    {% block template_conf_content %}
    {%endblock%}
    <title> {% block title%} {% endblock %} </title>
</head>
<body>

    <header>
        <nav class=" navbar navbar-inverse">
            <div class="container-fluid">
                <!--Inicio navbar header  -->
                <div class="navbar-header">
                    <!--Botón de collapse para disp moviles  -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-1" aria-expanded="false">
                        <span class="sr-only">Acultar-Mostrar navegación</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="{% url 'inicio'%}" class="navbar-brand">Blog</a>
                    <!--Fin navbar-header  -->
                </div>

                <!--Colleccion links de nav  -->
                <div class="collapse navbar-collapse" id="navbar-1">
                    <!--Inicia lista de menú  -->
                    <ul class="nav navbar-nav">
                        <li class="{% block active_about %}{% endblock %}"><a href="{% url 'about' %}">Acerca De</a></li>
                        <li class="{% block active_contact %}{% endblock %}"><a href="{% url 'contacto' %}"></span>Contacto</a></li>
                    </ul>

                    <!--Formulario de búsqueda  -->
                     <from class="navbar-form navbar-left">
                        <div class="form-group">
                            <input name='publicacion' type="text" class="form-control" placeholder="Buscar">
                        </div>
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>

                    </from>

                    <!--Links derechos  -->
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#"><span class="glyphicon glyphicon-off"></span>Logout</a></li>
                    </ul>

                    <!--Fin Colleccion links de nav  -->
                </div>
                <!--Fin container-fluid  -->
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        {% block body%}
        {% endblock %}

    </div>


    <script src="{% static 'js/jquery.min.js' %}"> </script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="../static/js/jquery.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>

</body>
</html>

blog/templates/contacto.html
{% extends 'base.html' %}
{% block title%} Contacto {% endblock %}

{% block template_conf_content %}

{%endblock%}
{% block active_contact %}active{% endblock %}
{% block body%}
        <div class="row">
            <div class="col-xs-12 col-md-5 col-md-offset-3 bg-info">
                <h3>Llena el formulario y nos pondremos en contacto con tigo.</h3>
                <form action="" class=" form-horizontal" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class=" form-group">
                        <div class="col-xs-12 col-md-2">
                            {{field.label_tag}}
                        </div>

                            {{field}}

                    </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-md-offset-5">
                            <button type="submit" class="btn btn-success">
                                Enviar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

blog/templates/incio.html
{% extends 'base.html' %}
{% block title%} Inicio{% endblock}

{% block body%}
        <div class="list-group">
            {% for publicacion in lista_publicaciones%}
            <a href="" class=" list-group-item">
                <h4 class="list-group-item-heading"> {{publicacion.titulo}} </h4>
                <p class="list-group-item-text">
                    {{publicacion.contenido|truncatewords:80}}
                    ...
                </p>
            </a>
            {% endfor %}
        </div>
{% endblock}

blog/templates/inicio.html
{% extends 'base.html' %}
{% block title%} Inicio{% endblock %}

{% block body%}
        <style>
            .jumbotron{
                background-color: #4fca42;/* #428bca;*/
                color:#fff;
                
            }
            .jumbotron .btn-success{
                border-color: #eee;
                padding-left: 50px;
                padding-right:50px;
            }
        </style>
        <div class="row">
            <div class="jumbotron">
                <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas.</h2>
                <br>
                <a href="#" class="btn btn-success"> Crea una cuenta.</a>
                <br>
                <br>
                
            </div>
        </div>

        <div class="row">
            <section class=" col-xs-12 col-sm-7 col-md-8">
                <h2 class="section-title">Publicaciones recientes.</h2>
                
                <div class="list-group">
                    {% for publicacion in lista_publicaciones %}
                    <a href="{% url 'publicaciones:detalle' publicacion.titulo_formato %}" class=" list-group-item">
                        <h4 class="list-group-item-heading"> {{publicacion.titulo}} </h4>
                        <p class="list-group-item-text">
                            {{publicacion.contenido|truncatewords:80}}
                            ...
                        </p>
                    </a>
                    {% endfor %}
                </div>
            </section>
            <div class=" col-sm-4 col-md-3 hidden-xs">
                <br>
                <br>
                <br>
                <div class="side-bar list-group">
                    <span><h3>Categorías</h3></span>
                    <hr>
                    <a class="active list-group-item">Profile</a>
                    <a class="list-group-item">Profile</a>
                    <a class="list-group-item">Profile</a>
                    <a class="list-group-item">Profile</a>
                    <a class="list-group-item">Profile</a>
                    
                </div>
            </div>
        </div>
                
{% endblock %}

blog/templates/publicaciones/detalle_publicacion.html
{% extends 'base.html' %}
{% block title%} Publicacion {{ publicacion.titulo|truncatewords:5 }}...{% endblock %}
{% block body%}
        <div class="container">
            <div class="row">
                <section>
                    <h2 class="section-title">{{ publicacion.titulo }}</h2>
                      <a href="{% url 'publicaciones:modificarPublicacion' publicacion.titulo_formato %}">
                        <button type="submit" class="btn btn-default">Modificar</button>
                      </a>
                    <p class="col-xs-12 col-md-8 col-md-offset-2">
                        {{ publicacion.contenido }}
                    </p>
                </section>
            </div>

            <div class="row">
                <section class="">
                    <h3 class="section-title">Comentarios</h2>

                    <div class="comentarios col-md-12">
                    {% for comentario in publicacion.comentario_set.all %}
                        <div class="comentario">
                            <a href="">{{comentario.fecha}}</a>
                            <br>
                            {{ comentario.contenido }}
                        </div>
                    {% endfor %}
                    </div>
                    <form action="" class="col-xs-12 col-md-6 col-md-offset-3 " method="POST">
                      {% csrf_token %}
                        {{form.contenido.label_tag}}
                        {{form.contenido}}
                        <input type="text" hidden name="publicacion" value="{{publicacion.id}}">
                        <button type="submit" class="btn btn-default" action="" method="POST">Enviar</button>
                        {% csrf_token %}
                    </form>

                </section>
            </div>
        </div>


{% endblock %}

blog/templates/publicaciones/form_publicacion.html
{% extends 'base.html' %}

{% block title %} Crear Publicación {% endblock %}

{% block template_conf_content %}
{%endblock%}


{% block body%}
        <div class="row">
            <div class="col-xs-12 col-md-5 col-md-offset-3 bg-info">
              {% ifequal flag 'modificar' %}
                <h2>Modificar.</h2>
              {% endifequal %}
              {% ifequal flag 'nuevo' %}
                <h2>Nueva Publicacion.</h2>
              {% endifequal %}
                <form action="" class=" form-horizontal" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class=" form-group">
                        <div class="col-xs-12 col-md-2">
                            {{field.label_tag}}
                        </div>

                            {{field}}

                    </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-md-offset-5">
                            <button type="submit" class="btn btn-success">
                                Guardar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}